main: SVega9848\VegaReload\Loader
version: 1.1.0
name: VegaReload
api: [5.5.0]
author: SVega9848
website: https://www.youtube.com/@Jayseba04

permissions:
  vegareload.cmd:
    description: Reload command
    default: op
